version: "2"
linters:
  enable:
    - misspell
    - revive
    - sloglint
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/SuperQ/smokeping_prober)
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/SuperQ/smokeping_prober
