apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smokeping.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smokeping.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ tpl (toYaml .Values.config) . | nindent 4 }}