{{- if .Values.prometheus.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "smokeping.fullname" . }}-prometheus
rules:
- apiGroups: [""]
  resources:
  - "*"
  verbs: ["get", "list", "watch"]
{{end}}