{{- if .Values.prometheus.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "smokeping.fullname" . }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "smokeping.fullname" . }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ include "smokeping.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
{{end}}